### ISSUE TITLE
基金回测，如果回测日期超过已有数据范围，则会报Key-Error错误

### ISSUE THREAD

**Issue by shwdbd** [shwdbd/equan#7]
如果数据文件中数据范围是 **[2020-01-01 , 2020-03-20]**
回测日期是 **[2020-01-01 , 2020-03-31]**
则回测框架执行到 3/23 日时，会报 KeyError: '2020-03-23'错误

错误信息如下：
```
Traceback (most recent call last):
  File "C:\python\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '2020-03-23'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/python/workspace/equan/src/equan/fund/my_code/my_aip.py", line 93, in <module>
    strategy.run()
  File "C:\python\workspace\equan\src\equan\fund\fund_backtesting.py", line 81, in run
    self.date_handle(self.get_context())   # 调用用户的策略初始化
  File "c:/python/workspace/equan/src/equan/fund/my_code/my_aip.py", line 52, in date_handle
    week = df.loc[context.today, '星期']
  File "C:\python\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "C:\python\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 868, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\python\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 988, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "C:\python\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1913, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\python\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 141, in _get_label
    return self.obj._xs(label, axis=axis)
  File "C:\python\Anaconda3\lib\site-packages\pandas\core\generic.py", line 3585, in xs
    loc = self.index.get_loc(key)
  File "C:\python\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '2020-03-23'
```

**Comment by shwdbd** [comment]
原因在于：
初始化acct.df的时候，没有那天的数据，即df中没有那一行的数据。用户在调用df.loc[2020-03-25,]就会出现KeyError的错误

**Comment by shwdbd** [comment]
建议：
1. 客户端进行数据有效性的检查，避免出现KeyError情况
2. 并在装载数据的时候，检查哪些天没有数据，在日志Error中显示。如果是历史数据没有，或end_date未超过系统日期就出现没数的情况，提供应该提示

**Comment by shwdbd** [comment]
建议：修改框架，如果当日没有数据则直接跳过这天，不执行，并进行日志报警；

**Comment by shwdbd** [comment]
在 v0.1.1版本中已修复
